### ISSUE TITLE
Linking Error: undefined reference to symbol 'inflateEnd'

### ISSUE THREAD

**Issue by YuMao1993** [johmathe/Shotdetect#18]
/usr/bin/ld: /home/mscvproject/install/usr/lib/libavformat.a(http.o): undefined reference to symbol 'inflateEnd'
/home/mscvproject/install/usr/lib/libz.so.1: error adding symbols: DSO missing from command line
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/shotdetect-cmd.dir/build.make:129: recipe for target 'shotdetect-cmd' failed
make[2]: *** [shotdetect-cmd] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/shotdetect-cmd.dir/all' failed
make[1]: *** [CMakeFiles/shotdetect-cmd.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by YuMao1993** [comment]
I am working on Ubuntu 16.04 and I am trying to build the command line tool.
